port: 4567
debug: false
useKeyAuth: false
key: 'change_me'
normalizeMessages: true

# Use this list to set allowed CORS Origins ("*" by default)
corsOrigins:
  - "*"

# Example webhook configuration
#webhooks:
#  default:
#    listener: "https://your-webhook-target.com/whatever"
#    events:
#      - PlayerJoin
#      - PlayerQuit
#      - PlayerKick
#      - PlayerDeath
#      - PlayerChat

# Number of console log lines to send when websocket connections are opened
# Set to 0 to effectively disable this
websocketConsoleBuffer: 1000
