name: Build ServerTap

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 17
    - name: Build and Run Tests
      run: mvn test --batch-mode --fail-at-end
    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Clean up artifacts
      run: rm target/original-*.jar
    - uses: actions/upload-artifact@v2
      with:
        name: Release
        path: target/*.jar
